# Generated by Django 4.2.9 on 2024-01-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitit_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
