# Generated by Django 4.2.9 on 2024-01-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitit_api', '0002_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroups',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
